//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RibbonUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FirstRun {
            get {
                return ((bool)(this["FirstRun"]));
            }
            set {
                this["FirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SearchFolders {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SearchFolders"]));
            }
            set {
                this["SearchFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(Default)")]
        public global::System.Globalization.CultureInfo UICulture {
            get {
                return ((global::System.Globalization.CultureInfo)(this["UICulture"]));
            }
            set {
                this["UICulture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection KnownSubtitleFormatsAdded {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["KnownSubtitleFormatsAdded"]));
            }
            set {
                this["KnownSubtitleFormatsAdded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection KnownSubtitleFormatsRemoved {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["KnownSubtitleFormatsRemoved"]));
            }
            set {
                this["KnownSubtitleFormatsRemoved"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Frost.Common.Util.SerializableStringDictionary AudioCodecIdBindingsAdded {
            get {
                return ((global::Frost.Common.Util.SerializableStringDictionary)(this["AudioCodecIdBindingsAdded"]));
            }
            set {
                this["AudioCodecIdBindingsAdded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Frost.Common.Util.SerializableStringDictionary AudioCodecIdBindingsRemoved {
            get {
                return ((global::Frost.Common.Util.SerializableStringDictionary)(this["AudioCodecIdBindingsRemoved"]));
            }
            set {
                this["AudioCodecIdBindingsRemoved"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Frost.Common.Util.SerializableStringDictionary VideoCodecIdBindingsAdded {
            get {
                return ((global::Frost.Common.Util.SerializableStringDictionary)(this["VideoCodecIdBindingsAdded"]));
            }
            set {
                this["VideoCodecIdBindingsAdded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Frost.Common.Util.SerializableStringDictionary VideoCodecIdBindingsRemoved {
            get {
                return ((global::Frost.Common.Util.SerializableStringDictionary)(this["VideoCodecIdBindingsRemoved"]));
            }
            set {
                this["VideoCodecIdBindingsRemoved"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Frost.Common.Util.SerializableStringDictionary KnownSegmentsAdded {
            get {
                return ((global::Frost.Common.Util.SerializableStringDictionary)(this["KnownSegmentsAdded"]));
            }
            set {
                this["KnownSegmentsAdded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Frost.Common.Util.SerializableStringDictionary KnownSegmentsRemoved {
            get {
                return ((global::Frost.Common.Util.SerializableStringDictionary)(this["KnownSegmentsRemoved"]));
            }
            set {
                this["KnownSegmentsRemoved"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Frost.Common.Util.SerializableStringDictionary CustomLanguageMappingsAdded {
            get {
                return ((global::Frost.Common.Util.SerializableStringDictionary)(this["CustomLanguageMappingsAdded"]));
            }
            set {
                this["CustomLanguageMappingsAdded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Frost.Common.Util.SerializableStringDictionary CustomLanguageMappingsRemoved {
            get {
                return ((global::Frost.Common.Util.SerializableStringDictionary)(this["CustomLanguageMappingsRemoved"]));
            }
            set {
                this["CustomLanguageMappingsRemoved"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ExcludedSegmentsAdded {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ExcludedSegmentsAdded"]));
            }
            set {
                this["ExcludedSegmentsAdded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ExcludedSegmentsRemoved {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ExcludedSegmentsRemoved"]));
            }
            set {
                this["ExcludedSegmentsRemoved"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ReleaseGroupsAdded {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ReleaseGroupsAdded"]));
            }
            set {
                this["ReleaseGroupsAdded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ReleaseGroupsRemoved {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ReleaseGroupsRemoved"]));
            }
            set {
                this["ReleaseGroupsRemoved"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection KnownSubtitleExtensionsAdded {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["KnownSubtitleExtensionsAdded"]));
            }
            set {
                this["KnownSubtitleExtensionsAdded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection KnownSubtitleExtensionsRemoved {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["KnownSubtitleExtensionsRemoved"]));
            }
            set {
                this["KnownSubtitleExtensionsRemoved"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection KnownVideoExtensionsAdded {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["KnownVideoExtensionsAdded"]));
            }
            set {
                this["KnownVideoExtensionsAdded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection KnownVideoExtensionsRemoved {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["KnownVideoExtensionsRemoved"]));
            }
            set {
                this["KnownVideoExtensionsRemoved"] = value;
            }
        }
    }
}
