//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frost.Providers.Xbmc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Frost.Providers.Xbmc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ----------------------------
        ///-- Table structure for &quot;EdmMetadata&quot;
        ///-- ----------------------------
        ///CREATE TABLE IF NOT EXISTS &quot;EdmMetadata&quot; (
        ///	&quot;Id&quot;  TEXT,
        ///	&quot;ModelHash&quot;  TEXT
        ///);
        ///
        ///-- ----------------------------
        ///-- Table structure for &quot;__MigrationHistory&quot;
        ///-- ----------------------------
        ///CREATE TABLE IF NOT EXISTS &quot;__MigrationHistory&quot; (
        ///	&quot;ContextKey&quot; TEXT,
        ///	&quot;MigrationId&quot;  TEXT NOT NULL,
        ///	&quot;Model&quot;  BLOB NOT NULL,
        ///	&quot;ProductVersion&quot;  TEXT NOT NULL
        ///);.
        /// </summary>
        internal static string addEfTables {
            get {
                return ResourceManager.GetString("addEfTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN TRANSACTION;
        ///
        ///CREATE TEMPORARY TABLE 
        ///settings_backup (
        ///	idFile INTEGER,
        ///	Deinterlace BOOLEAN,
        ///	ViewMode INTEGER,
        ///	ZoomAmount FLOAT,
        ///	PixelRatio FLOAT,
        ///	VerticalShift FLOAT,
        ///	AudioStream INTEGER,
        ///	SubtitleStream INTEGER,
        ///	SubtitleDelay FLOAT,
        ///	SubtitlesOn BOOLEAN,
        ///	Brightness FLOAT,
        ///	Contrast FLOAT,
        ///	Gamma FLOAT,
        ///	VolumeAmplification FLOAT,
        ///	AudioDelay FLOAT,
        ///	OutputToAllSpeakers BOOLEAN,
        ///	ResumeTime INTEGER,
        ///	Crop BOOLEAN,
        ///	CropLeft INTEGER,
        ///	CropRight INTEGER,
        ///	CropTop INTEGE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string extendSettings {
            get {
                return ResourceManager.GetString("extendSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN TRANSACTION;
        ///
        ///CREATE TEMPORARY TABLE 
        ///streamdetails_backup (
        ///	idFile integer,
        ///	iStreamType integer,
        ///	strVideoCodec text,
        ///	fVideoAspect float,
        ///	iVideoWidth integer,
        ///	iVideoHeight integer,
        ///	strAudioCodec text,
        ///	iAudioChannels integer,
        ///	strAudioLanguage text,
        ///	strSubtitleLanguage text,
        ///	iVideoDuration integer
        ///);
        ///
        ///INSERT INTO streamdetails_backup SELECT * FROM streamdetails;
        ///DROP TABLE streamdetails;
        ///
        ///CREATE TABLE
        ///streamdetails (
        ///	idStream integer primary key not null,
        ///	idFile integ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StreamDetailsPK {
            get {
                return ResourceManager.GetString("StreamDetailsPK", resourceCulture);
            }
        }
    }
}
